dj4e-market/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, re_path
from django.contrib.auth import views as auth_views
from django.views.static import serve
import os

urlpatterns = [
    path('', include('mkt.urls')),
    path('home/', include('home.urls')),
    path('pics/', include('pics.urls')),
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]   
    
# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')
    

dj4e-market/mkt/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='mkt'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('mkt:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('mkt:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/toggle', views.ToggleFavoriteView.as_view(), name='ad_toggle'),
]

dj4e-market/mkt/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from taggit.managers import TaggableManager

class Ad(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    
    tags = TaggableManager(blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='comments_owned')
    # Favorites
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favorite_ads')
    
    # Picture
    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True,
        help_text='The MIMEType of the file')
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title
    
class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'
    
class Fav(models.Model) :
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/4.2/ref/models/options/#unique-together
    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.ad.title[:10])

dj4e-market/mkt/forms.py
from django import forms
from django.core import validators
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.exceptions import ValidationError

from mkt.models import Ad, Comment
from mkt.humanize import naturalsize


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Ad
        fields = ['title', 'text', 'picture', 'price', 'tags'] 

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")
            
    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m() 

        return instance

class CommentForm(forms.Form):    
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

dj4e-market/mkt/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.http import HttpResponse
from django.db.models import Q

from mkt.models import Ad, Comment, Fav
from mkt.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from mkt.forms import CreateForm, CommentForm

# Create your views here.
class AdListView(OwnerListView):
    model = Ad
    template_name = "mkt/ad_list.html"
    
    def get(self, request):
        strval = request.GET.get("search", False)
        
        if strval:
            query = Q(title__contains=strval)
            query.add(Q(text__contains=strval), Q.OR)
            query.add(Q(tags__name__in=[strval]), Q.OR)
            ad = Ad.objects.filter(query)
        else:
            ad = Ad.objects.all()
            
        favorites = list()
        if request.user.is_authenticated:
            rows = request.user.favorite_ads.values('id')
            favorites = [ row['id'] for row in rows ]
        ctx = {'ad_list' : ad, 'favorites': favorites}
        return render(request, self.template_name, ctx)


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = "mkt/ad_detail.html"
    
    def get(self, request, pk):
        ad = Ad.objects.get(id=pk)
        comments = Comment.objects.filter(ad=ad).order_by('-updated_at')
        comment_form = CommentForm()
        context = {'ad': ad, 'comments': comments, 'comment_form': comment_form}    
        return render(request, self.template_name, context)

class AdCreateView(LoginRequiredMixin, View):
    template_name = 'mkt/form.html'
    success_url = reverse_lazy('mkt:all')
    
    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)
    
    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()  
        form.save_m2m()
        return redirect(self.success_url)

class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'mkt/form.html'
    success_url = reverse_lazy('mkt:all')
    def get(self, request, pk):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        
        form = CreateForm(instance=ad)
        comment_form = CommentForm()
        ctx = {
            'form': form, 
            'comment_form':comment_form
        }
        
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=ad)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        ad = form.save(commit=False)
        ad.save()
        return redirect(self.success_url)

class AdDeleteView(OwnerDeleteView):
    model = Ad
    
def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        ad = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=ad)
        comment.save()
        return redirect(reverse('mkt:ad_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "mkt/ad_confirm_delete.html"

    def get_success_url(self):
        ad = self.object.ad
        return reverse('mkt:ad_detail', args=[ad.id])
    
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class ToggleFavoriteView(LoginRequiredMixin, View):

    def post(self, request, pk) :
        ad = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=ad)
        try:
            fav.save()
            return HttpResponse("Favorite added 42")
        except IntegrityError:  # Already there, lets delete...
            Fav.objects.get(user=request.user, ad=ad).delete()
            return HttpResponse("Favorite deleted 42")

dj4e-market/mkt/templates/mkt/ad_confirm_delete.html
{% extends "base_menu.html" %}

{% block content %}

<h1>Delete Ad</h1>

<p>Are you sure you want to delete the Ad: {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'mkt:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

dj4e-market/mkt/templates/mkt/ad_detail.html
{% extends "base_menu.html" %}
{% load humanize %}

{% block head %}
  <style>
  .overlay{
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 10;
    display: none;
    background-color: rgba(0,0,0,0.5); /*dim the background*/
  }
  </style>
{% endblock %}

{% block content %}
  {% if ad.content_type %}
    <div id="overlay" class="overlay" style="text-align: center;"
      onclick="document.getElementById('overlay').style.display = 'none';" >
      <img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'mkt:ad_picture' ad.id %}">
    </div>
  {% endif %}

  <span style="float: right;">
  ({{ ad.updated_at|naturaltime }})

  {% if ad.owner == user %}
    <a href="{% url 'mkt:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
    <a href="{% url 'mkt:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
  {% endif %}
  </span>
  <h1>{{ ad.title }}</h1>
  {% if ad.content_type %}
    <img style="float:right; max-width:50%;" src="{% url 'mkt:ad_picture' ad.id %}"
        onclick="document.getElementById('overlay').style.display = 'block';">
  {% endif %}
  <p>
    {{ ad.text }}
  </p>
  <p>
    Price: {{ad.price}}
  </p>
  <p>
    <a href="{% url 'mkt:all' %}">All Market</a>
  </p>
  {% if user.is_authenticated %}
    <br clear="all"/>
    <p>
      {% load crispy_forms_tags %}
      <form method="post" action="{% url 'mkt:ad_comment_create' ad.id %}">
          {% csrf_token %}
          {{ comment_form|crispy }}
        <input type="submit" value="Submit">
      </form>
    </p>
  {% endif %}
  {% for comment in comments %}
    <p> {{ comment.text }} 
      ({{ comment.updated_at|naturaltime }})
      {% if user == comment.owner %}
        <a href="{% url 'mkt:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
      {% endif %}
    </p>
  {% endfor %}
  {% endblock %}

dj4e-market/mkt/templates/mkt/ad_form.html
{% extends "base_menu.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'mkt:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

dj4e-market/mkt/templates/mkt/ad_list.html
{% extends "base_menu.html" %}

{% block content %}
  <div style="float:right">
  <form>
    <input type="text" placeholder="Search.." name="search"
    {% if search %} value="{{ search }}" {% endif %}
    >
    <button type="submit"><i class="fa fa-search"></i></button>
  <a href="{% url 'mkt:all' %}"><i class="fa fa-undo"></i></a>
  </form>
  </div>

  <h1>Market</h1>
  {% if ad_list %}
  <ul>
    {% for ad in ad_list %}
      <li>
          <a href="{% url 'mkt:ad_detail' ad.id %}">{{ ad.title }}</a>
          {% if ad.owner == user %}
            (<a href="{% url 'mkt:ad_update' ad.id %}">Update</a> |
            <a href="{% url 'mkt:ad_delete' ad.id %}">Delete</a>)
          {% endif %}
          {% if user.is_authenticated %}
            <dj4e-favstar 
                onclick="favToggle(this, '{% url 'mkt:ad_toggle' ad.id %}');"
                {% if ad.id in favorites %} fav {% endif %} 
            >
            </dj4e-favstar>
          {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no ads in the library.</p>
  {% endif %}
  <p>
  <a href="{% url 'mkt:ad_create' %}">Add a AD</a>
  </p>

  <script>  
  function favToggle(element, url) {
      console.log('POSTing to', url);
      fetch(url, { method: 'POST', body: '{}' } )
      .then((response) => {
          if (!response.ok) { // Check if the response status is in the 2xx range (success)
              console.log("If you see this error, it is likely in ToggleFavoriteView()");
              console.log("Note: It is easier to diagnose this error FireFox.");
              throw new Error(`AJAX/fetch error status: ${response.status}, see developer console.`)
          }
          return response.text();
      })
      .then((response) => {
          console.log(url, response);
          element.toggleAttribute('fav');
      }).catch((error) => {
          alert(`Url ${url} failed ${error}`);
      });
  }
  </script>
  <script type="module" src="/site/wc/dj4e-favstar.js"></script>
{% endblock %}

dj4e-market/mkt/templates/mkt/form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'mkt:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
document.getElementById("upload_form").addEventListener("submit", function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = document.getElementById('id_{{ form.upload_field_name }}').files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}